# Broken GitHub Actions workflow for Demo 2
# This workflow has multiple issues that Amazon Q will fix

name: Deploy to Production
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # ISSUE: No AWS authentication
      - name: Deploy Infrastructure
        run: terraform apply -auto-approve

      # ISSUE: No Terraform initialization
      # ISSUE: No validation step
      # ISSUE: No planning step
      # ISSUE: Auto-approve is dangerous for production
      # ISSUE: No approval gate
      # ISSUE: No error handling
      # ISSUE: No notifications
      # ISSUE: Runs on every push (even to feature branches)
